sudo: required
services:
  - docker


before_install:
  - docker build -t avnrc/simpleweb -f Dockerfile .

script:
  - docker run -d -p 8080:8080 avnrc/simpleweb

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-SimpleApp"
  env: "DockerSimpleapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-270434586602"
  bucket_path: "Docker-SimpleApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

